### PR TITLE
caa: fix critical flag according to rfc8659

### PR DESCRIPTION
**Pull request by MarcelCoding**
https://datatracker.ietf.org/doc/html/rfc8659#name-critical-flag

### CODE REVIEW

**Comment by kirelagin** [comment]
Could you please a comment explaining the logic of this? I believe, 4.1 is the relevant reference.

**Comment by SuperSandro2000** [comment]
also see https://letsencrypt.org/docs/caa/#what-to-put-in-the-record

**Comment by kirelagin** [comment]
I’ve looked at the linked section: there is nothing there that explains the format of the flags field and nothing that says _which_ bit or the one. Both of these are specified in 4.1.

**Comment by MarcelCoding** [comment]
Hi, I actually found that the section that you referenced explains this way better:
(I've highlighted the corresponding parts.)

**Comment by SuperSandro2000** [comment]
Can this PR be merged? Otherwise CAA records do not work as expected.

**Pull request merged**
